Vagrant.configure("2") do |config|

    config.vm.box = "iamaleks/Ubuntu-18.04"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "hyperv" do |h|
        h.auto_start_action = 'Nothing'
        h.auto_stop_action = 'ShutDown'
        h.cpus = 1
        h.maxmemory = 2048
        h.memory = 1024
        h.vmname = 'VM01'
    end
  
    # config.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL

  end
